#! /bin/sh
### BEGIN INIT INFO
# Provides:		    elasticsearch
# Required-Start:	$syslog $remote_fs
# Required-Stop:	$syslog $remote_fs
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	elasticsearch - Distributed, RESTful search and analytics
# Description:		elasticsearch - Distributed, RESTful search and analytics
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/elasticsearch/bin/elasticsearch
NAME=elasticsearch
DESC=elasticsearch

RUNDIR=/var/run/elasticsearch
PIDFILE=$RUNDIR/elasticsearch.pid
ULIMIT=65535

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

set -e

if [ "$(id -u)" != "0" ]
then
	log_failure_msg "Must be run as root."
	exit 1
fi

case "$1" in
  start)
	echo -n "Starting $DESC: "
	mkdir -p $RUNDIR
	touch $PIDFILE
	chown lirizhong:lirizhong $RUNDIR $PIDFILE
	chmod 755 $RUNDIR $PIDFILE

	if [ -n "$ULIMIT" ]
	then
		ulimit -n $ULIMIT || true
	fi

	if sudo -u lirizhong $DAEMON -d -p $PIDFILE
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "

	if start-stop-daemon --stop --retry forever/TERM/1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	then
		echo "$NAME."
	else
		echo "failed"
	fi
	rm -f $PIDFILE
	sleep 1
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;

  status)
	status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
	;;

  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
